name: 'Secret (input) gate'
description: 'Allows checking if some values are set and optionally fail if they arent.'
inputs:
  inputsToCheck:
    description: 'comma separated list of inputs to check.'
    required: true
  failOnMissing:
    description: 'Should the action fail if some input has no value?'
    default: 'false'
outputs:
  inputsChecked:
    description: 'True for no values missing'
branding:
  icon: 'check-circle'
  color: 'orange'
runs:
  using: 'node12'
  main: 'dist/index.js'
